[book]
authors = ["s2301089"]
language = "en"
multilingual = false
src = "src"
title = "development-CubeIDE"

[output.html]
mathjax-support = true

[preprocessor.image-size]
command = "mdbook-image-size"